name: Deploy Google Cloud Run
on:
  push:
  #workflow_run:
  #  workflows: ["dockerImage"]
  #  types:
  #      - completed
  
jobs:
  deploy:
    runs-on: ubuntu-latest

############################# CHECK IF NEEDED ########################
    permissions:  # Korrekte Berechtigungen für den Job
      contents: read
      id-token: write
      packages: read
######################################################################

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log repository details
        run: |
          echo "Repository: ${{ github.repository }}"
          echo "Branch: ${{ github.ref_name }}"

      - name: Authenticate to Google Cloud (with workload identity federation)
        uses: google-github-actions/auth@v2
        with:
          token_format: 'access_token'
          workload_identity_provider: 'projects/70756149774/locations/global/workloadIdentityPools/github-actions/providers/github-repos' #'${{secrets.WORKLOAD_IDENTITY_PROVIDER}}'
          service_account: 'hshn-devsecops-service-account@hs-heilbronn-devsecops.iam.gserviceaccount.com' #'${{secrets.SERVICE_ACCOUNT}}'

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: hs-heilbronn-devsecops

      #- name: Log in to GitHub Container Registry
      #  uses: docker/login-action@v3
      #  with:
      #    registry: ghcr.io
      #    username: ${{ github.actor }}  # GitHub-Username (added automatically)
      #    password: ${{ secrets.GITHUB_TOKEN }}  # GitHub Token for authentication

      

      - name: Authenticate Docker with Google Artifact Registry
        run: gcloud auth configure-docker europe-west3-docker.pkg.dev

      - name: Push Docker image to Google Artifact Registry
        run: |
          sudo apt-get -y install skopeo
          --dest-creds="oauth2accesstoken:$(gcloud auth print-access-token)" \
          skopeo login -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }} ghcr.io
          skopeo copy \
            --debug \
            docker://ghcr.io/hs-heilbronn-devsecops-mjmteam/note-api/note-api:latest \
            docker://europe-west3-docker.pkg.dev/hs-heilbronn-devsecops-mjmteam/note-api/note-api:latest 

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: note-api #hs-heilbronn-devsecops-mjmteam/note-api
          image: ghcr.io/hs-heilbronn-devsecops-mjmteam/note-api:latest
          region: europe-west3 #Frankfurt ?
          env_vars: BACKEND=memory